# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoTrack Therapy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoTrack Therapy (Core includes analytics by default)
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'

end
